// auth
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

// Create App
export const UPLOAD_NEW_APP_FAILED = 'UPLOAD_NEW_APP_FAILED';
export const UPLOAD_NEW_APP_START = 'UPLOAD_NEW_APP_START';
export const UPLOAD_NEW_APP_SUCCESS = 'UPLOAD_NEW_APP_SUCCESS';
export const RESET_NEW_APP = 'RESET_NEW_APP';
export const SET_FILE_OBJECT = 'SET_FILE_OBJECT';

// account settings
export const FETCH_ACCOUNT_SETTINGS_FAILED = 'SET_ACCOUNT_SETTINGS_FAILED';
export const FETCH_ACCOUNT_SETTINGS_START = 'FETCH_ACCOUNT_SETTINGS_START';
export const SET_ACCOUNT_SETTINGS_SUCCESS = 'SET_ACCOUNT_SETTINGS_SUCCESS';
export const SET_ACCOUNT_SETTINGS = 'SET_ACCOUNT_SETTINGS';

// App List
export const DELETE_APP_FAILED = 'DELETE_APP_FAILED';
export const DELETE_APP_FORBIDDEN = 'DELETE_APP_FORBIDDEN';
export const DELETE_APP_START = 'DELETE_APP_START';
export const DELETE_APP_SUCCESS = 'DELETE_APP_SUCCESS';
export const FETCH_APP_FAILED = 'FETCH_APP_FAILED';
export const FETCH_APP_START = 'FETCH_APP_START';
export const FETCH_APP_SUCCESS = 'FETCH_APP_SUCCESS';
export const RESET_APP_STATE = 'RESET_APP_STATE';

// App Details
export const FILE_INPUT_CHANGED_HANDLER_AD = 'FILE_INPUT_CHANGED_HANDLER_AD';
export const INPUT_CHANGED_HANDLER_AD = 'INPUT_CHANGED_HANDLER_AD';
export const LOAD_APP_DETAILS = 'LOAD_APP_DETAILS';
export const RESET_APP_DETAILS = 'RESET_APP_DETAILS';
export const RESET_FILE_INPUTS = 'RESET_FILE_INPUTS';
export const SET_DOWNLOAD_URLS = 'SET_DOWNLOAD_URLS';
export const UPDATE_FILE_START = 'UPDATE_FILE_START';
export const UPDATE_LOADING_STATE = 'UPDATE_LOADING_STATE';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
