// auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const INPUT_CHANGED_HANDLER_AUTH = 'INPUT_CHANGED_HANDLER_AUTH';

// Create App
export const INPUT_CHANGED_HANDLER = 'INPUT_CHANGED_HANDLER';
export const FILE_INPUT_CHANGED_HANDLER = 'FILE_INPUT_CHANGED_HANDLER';

export const CREATE_APP_START = 'CREATE_APP_START';
export const CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS';
export const CREATE_APP_FAILED = 'CREATE_APP_FAILED';
export const SET_FILE_OBJECT = 'SET_FILE_OBJECT';
export const RESET_NEW_APP = 'RESET_NEW_APP';

// account settings
export const FETCH_ACCOUNT_SETTINGS_SUCCESS = 'FETCH_ACCOUNT_SETTINGS_SUCCESS';

// App List
export const FETCH_APP_START = 'FETCH_APP_START';
export const FETCH_APP_SUCCESS = 'FETCH_APP_SUCCESS';
export const FETCH_APP_FAILED = 'FETCH_APP_FAILED';
export const DELETE_APP_START = 'DELETE_APP_START';
export const DELETE_APP_SUCCESS = 'DELETE_APP_SUCCESS';
export const DELETE_APP_FAILED = 'DELETE_APP_FAILED';
export const DELETE_APP_FORBIDDEN = 'DELETE_APP_FORBIDDEN';
export const RESET_APP_STATE = 'RESET_APP_STATE';

// App Details
export const LOAD_APP_DETAILS = 'LOAD_APP_DETAILS';
export const INPUT_CHANGED_HANDLER_AD = 'INPUT_CHANGED_HANDLER_AD';
export const SET_DOWNLOAD_URLS = 'SET_DOWNLOAD_URLS';
export const FILE_INPUT_CHANGED_HANDLER_AD = 'FILE_INPUT_CHANGED_HANDLER_AD';
export const UPDATE_LOADING_STATE = 'UPDATE_LOADING_STATE';
export const RESET_APP_DETAILS = 'RESET_APP_DETAILS';
export const UPDATE_FILE_START = 'UPDATE_FILE_START';
export const RESET_FILE_INPUTS = 'RESET_FILE_INPUTS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
